var cities = [
	{ city: "London", country: "United Kingdom", index: 280 },
	{ city: "Geneva", country: "Switzerland", index: 259 },
	{ city: "New York City", country: "United States", index: 237 },
	{ city: "Singapore", country: "Singapore", index: 228 },
	{ city: "Paris", country: "France", index: 219 },
	{ city: "San Francisco", country: "United States", index: 218 },
	{ city: "Copenhagen", country: "Denmark", index: 217 },
	{ city: "Sydney", country: "Australia", index: 215 },
	{ city: "Hong Kong", country: "Hong Kong", index: 214 },
	{ city: "Brisbane", country: "Australia", index: 208 },
	{ city: "Stockholm", country: "Sweden", index: 204 },
	{ city: "Amsterdam", country: "Netherlands", index: 199 },
	{ city: "Tokyo", country: "Japan", index: 198 },
	{ city: "Washington D.C.", country: "United States", index: 197 },
	{ city: "Helsinki", country: "Finland", index: 192 },
	{ city: "Dublin", country: "Ireland", index: 191 },
	{ city: "Wellington", country: "New Zealand", index: 181 },
	{ city: "Munich", country: "Germany", index: 176 },
	{ city: "Toronto", country: "Canada", index: 175 },
	{ city: "Manchester", country: "United Kingdom", index: 175 },
	{ city: "Reykjavik", country: "Iceland", index: 173 },

];